CREATE TABLE "HR"."MEMBER2" 
   (	
   	"ID" VARCHAR2(10), 
	"PW" VARCHAR2(10), 
	"NAME" VARCHAR2(10), 
	"TEL" VARCHAR2(10)
   ) 
   
CREATE TABLE "HR"."BBS2"
(	
	"no" VARCHAR2(100),
	"TITLE" VARCHAR2(100),
	"CONTENT" VARCHAR2(100),
	"WRITER" VARCHAR2(100)
)

CREATE TABLE "HR"."PRODUCT2"(
ID VARCHAR2(200),
NAME VARCHAR2(200),
CONTENT VARCHAR2(200),
PRICE VARCHAR2(200),
COMPANY VARCHAR2(200),
IMG VARCHAR2(200)
)

-- 저장할 대상 : 엔티티(회원정보, 게시판, 상품)
-- 엔티티간의 관계 : 회원이 상품을 주문하다(주문정보)
-- 엔티티 + 관계 ==> 테이블로 만들자!

CREATE TABLE "HR"."ORDERLIST"
(
	"no" VARCHAR2(100),
	MEMBER_ID VARCHAR2(100),
	PRODUCT_ID VARCHAR2(100),
	TOTAL_COUNT VARCHAR2(100)
)

CREATE TABLE "HR"."DEPART2"(
ID VARCHAR2(100),
NAME VARCHAR2(100),
INSTRUCTOR VARCHAR2(100),
CONSTRAINT DEPART2_PK PRIMARY KEY (ID)
)

CREATE TABLE "HR"."STUDENT2"(
ID VARCHAR2(100),
NAME VARCHAR2(100),
TEL VARCHAR2(100),
DEPART_ID VARCHAR2(100)
)

--pk제약조건 추가
ALTER TABLE HR.STUDENT2
ADD CONSTRAINT STUDENT2_PK PRIMARY KEY (ID)

ALTER TABLE HR.STUDENT2 
ADD CONSTRAINT FK_DEPART22 
FOREIGN KEY (DEPART_ID) 
REFERENCES HR.DEPART2(ID)


CREATE TABLE "HR"."SUBJECT2"(
ID VARCHAR2(100),
TITLE VARCHAR2(100),
DEPART_ID VARCHAR2(100)
)

--pk제약조건 추가
ALTER TABLE HR.SUBJECT2
ADD CONSTRAINT SUBJECT2_PK PRIMARY KEY (ID)

ALTER TABLE HR.SUBJECT2 
ADD CONSTRAINT FK_DEPART222 
FOREIGN KEY (DEPART_ID) 
REFERENCES HR.DEPART2(ID)


CREATE TABLE "HR"."BBS3"(
"NO" VARCHAR2(100),
"TITLE" VARCHAR2(100),
"CONTENT" VARCHAR2(100),
"WRITER" VARCHAR2(100),
CONSTRAINT "BBS_PK3" PRIMARY KEY ("NO"),
CONSTRAINT "FK_MEMBER33" FOREIGN KEY ("WRITER")
REFERENCES "HR"."MEMBER"("ID")
)

CREATE TABLE "HR"."BBS4"(
"NO" VARCHAR2(100),
"TITLE" VARCHAR2(100),
"CONTENT" VARCHAR2(100),
"WRITER" VARCHAR2(100)
)

--pk제약조건 추가
ALTER TABLE HR.BBS4
ADD CONSTRAINT BBS4_PK PRIMARY KEY ("NO")

--fk제약조건 추가
ALTER TABLE HR.BBS4
ADD CONSTRAINT FK_MEMBER44
FOREIGN KEY (WRITER) REFERENCES HR."MEMBER"(ID)

CREATE TABLE hr.member22
AS SELECT * FROM member2

INSERT INTO hr.member22
VALUES ('banana','banana','banana','banana',sysdate)

SELECT * FROM hr.member22

INSERT INTO hr.member22
VALUES ('banana2','banana2','banana2','banana2',sysdate, 'aaa')

SELECT * FROM hr.member22


CREATE SEQUENCE pd_id_seq 
INCREMENT BY 1
START WITH 1

CREATE TABLE HR.product3(
	id number(38,0),
	name varchar2(100)
)

INSERT INTO product3 
VALUES (pd_id_seq.nextval, 'shoes')

SELECT * FROM product3

CREATE TABLE HR.ORDERLIST4 (
	id number(38,0),
	title varchar2(100),
	price number(38,0)
)

CREATE SEQUENCE or_seq 
INCREMENT BY 1
START WITH 1

INSERT INTO HR.ORDERLIST4 
VALUES (or_seq.nextval, 'shoes', '3000')

SELECT * FROM HR.ORDERLIST4

INSERT INTO HR.ORDERLIST4 
VALUES (or_seq.nextval, 'shoes', '4000')

SELECT * FROM HR.ORDERLIST4

INSERT INTO HR.ORDERLIST4 
VALUES (or_seq.nextval, 'shoes', '5000')

INSERT INTO HR.ORDERLIST4 
VALUES (or_seq.nextval, 'shoes', '6000')

INSERT INTO HR.ORDERLIST4 
VALUES (or_seq.nextval, 'shoes', '7000')

SELECT * FROM HR.ORDERLIST4
WHERE id >= 3
ORDER BY ID DESC 

INSERT INTO HR.BBS2 values(hr.bbs_id_seq.nextval, 't1', 'c1', 'apple')

SELECT * FROM HR.BBS2

CREATE TABLE HR.DEPT
(
DEPTNO NUMBER(2),
DNAME VARCHAR2(14 BYTE),
LOC VARCHAR2(13 BYTE)
)

CREATE TABLE HR.EMP
(
EMPNO NUMBER(4),
ENAME VARCHAR2(10 BYTE),
JOB VARCHAR2(9 BYTE),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2)
)

CREATE TABLE HR.SALGRADE
(
GRADE NUMBER,
LOSAL NUMBER,
HISAL NUMBER
)

ALTER TABLE HR.DEPT ADD (
CONSTRAINT PK_DEPT PRIMARY KEY(DEPTNO))

ALTER TABLE HR.EMP ADD (
CONSTRAINT PK_EMP PRIMARY KEY(EMPNO))

ALTER TABLE HR.EMP ADD (
CONSTRAINT FK_DEPTNO
FOREIGN KEY (DEPTNO)
REFERENCES HR.DEPT (DEPTNO))

SELECT * FROM HR.EMP -- Selection(행단위 검색)

SELECT DEPTNO FROM HR.EMP -- Projection(열단위 검색)

SELECT DISTINCT DEPTNO FROM HR.EMP --중복 제거

SELECT ENAME, SAL*12 AS YEARSAL FROM HR.EMP --AS YEARSAL : SAL*12를 YEARSAL로 나오게 해줌

SELECT * FROM HR.EMP ORDER BY SAL DESC --검색 다 끝나고 정렬

SELECT * FROM HR.EMP WHERE DEPTNO = 30 ORDER BY EMPNO DESC

SELECT * FROM HR.EMP WHERE NOT DEPTNO = 30 ORDER BY EMPNO DESC

SELECT * FROM HR.EMP WHERE DEPTNO != 30 ORDER BY EMPNO DESC

SELECT * FROM HR.EMP WHERE DEPTNO = 30 AND JOB = 'MANAGER'

SELECT * FROM HR.EMP WHERE JOB NOT IN ('SALESMAN','MANAGER') ORDER BY JOB 

SELECT * FROM HR.EMP WHERE SAL BETWEEN 2000 AND 3000 ORDER BY EMPNO 

SELECT * FROM HR.EMP WHERE ENAME LIKE '_L%'

SELECT * FROM HR.EMP WHERE ENAME NOT LIKE '_L%'

SELECT * FROM HR.EMP WHERE COMM IS NULL 

SELECT * FROM HR.EMP WHERE COMM IS NOT NULL 

CREATE TABLE HR.DEPT_TEMP2 AS SELECT * FROM HR.DEPT

SELECT * FROM HR.DEPT_TEMP2

UPDATE HR.DEPT_TEMP2 SET LOC = 'SEOUL'

UPDATE HR.DEPT_TEMP2 SET DNAME = 'DATABASE', LOC = 'BUSAN' WHERE DEPTNO = 40

DELETE FROM HR.DEPT_TEMP2 WHERE DNAME = 'SALES'

SELECT * FROM HR.DEPT_TEMP2

--1번
CREATE TABLE HR.PRODUCT4
(	
ID VARCHAR2(200),
NAME VARCHAR2(200),
CONTENT VARCHAR2(200),
PRICE NUMBER(38,0),
COMPANY VARCHAR2(200),
IMG VARCHAR2(200)
)

--2번
SELECT * FROM HR.PRODUCT4 ORDER BY PRICE DESC 

--3번
SELECT NAME, CONTENT, PRICE FROM HR.PRODUCT4 ORDER BY COMPANY ASC

--4번(중복제거)
SELECT DISTINCT COMPANY FROM HR.PRODUCT4

--5번
SELECT PRICE*5 AS PRICE5 FROM HR.PRODUCT4

--6번
SELECT NAME, COMPANY FROM HR.PRODUCT4 WHERE PRICE = 5000

--7번
SELECT NAME, PRICE, COMPANY FROM HR.PRODUCT4 WHERE PRICE BETWEEN 3000 AND 6000

--8번
SELECT COMPANY, NAME FROM HR.PRODUCT4 WHERE COMPANY != 'c100'

--9번
SELECT NAME, PRICE FROM HR.PRODUCT4 WHERE COMPANY = 'c100' OR COMPANY = 'c200'

--10번
SELECT * FROM HR.PRODUCT4 WHERE NAME LIKE '%4'

--11번
SELECT * FROM HR.PRODUCT4 WHERE CONTENT LIKE '%food%'

--12번
UPDATE HR.PRODUCT4 SET CONTENT = '품절' WHERE PRICE = 5000

--13번
UPDATE HR.PRODUCT4 SET IMG = 'o.png', PRICE = 10000 WHERE ID = '100' OR ID = '102'

--14번(회사명이 c100인 경우 모든 정보 삭제)
DELETE FROM HR.PRODUCT4 WHERE COMPANY = 'c100'

--15번(테이블의 모든 정보 삭제)
DELETE FROM HR.PRODUCT4