CREATE TABLE "HR"."BOARD2" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"DATECREATED" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   )
   
-- 추천게시판(recommend)

CREATE TABLE recommend(
	re_no number(38,0),
	title varchar2(100),
	content varchar2(100),
	writer varchar2(100)
)

DROP TABLE RECOMMEND 

CREATE TABLE recommend(
	re_no number(38,0),
	title varchar2(100),
	content varchar2(100),
	writer varchar2(100)
)

DROP TABLE RECOMMEND

CREATE TABLE recommend(
	re_no number(38,0),
	title varchar2(100),
	content varchar2(100),
	writer varchar2(100)
)

CREATE TABLE "HR"."BOARD3" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"DATECREATED" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   )

 ALTER TABLE HR.BOARD3 DROP COLUMN TEST2;
 
ALTER TABLE HR.BOARD3 DROP COLUMN TEST3;

ALTER TABLE HR.RECOMMEND MODIFY TITLE VARCHAR2(333);


DROP TABLE BOARD3

CREATE USER apple IDENTIFIED BY a1234

GRANT CONNECT, resource, dba TO apple

INSERT INTO MEMBER VALUES ('100','100','PARK','011')

INSERT INTO MEMBER VALUES ('200','200','PARK','011')

INSERT INTO MEMBER VALUES ('300','300','PARK','011')

SELECT * FROM "MEMBER"

SELECT * FROM MEMBER WHERE ID = '100' -- ID가 100인 모든 컬럼

SELECT ID FROM MEMBER WHERE ID = '100' -- ID가 100인 ID 컬럼

SELECT ID, NAME FROM MEMBER WHERE ID = '100' -- ID가 100인 ID, NAME 컬럼

SELECT NAME, ID FROM MEMBER WHERE ID = '100' -- ID가 100인 ID, NAME 컬럼

SELECT ID AS 아이디, NAME FROM MEMBER WHERE ID = '100'

SELECT TEL FROM MEMBER WHERE NAME = 'PARK'



UPDATE MEMBER SET NAME = 'KIM' WHERE ID = '100'

UPDATE MEMBER SET NAME = 'LEE' WHERE ID = '300'

UPDATE MEMBER SET PW = '8888', TEL = '999' WHERE ID = '200'

DELETE FROM MEMBER WHERE ID = '100'

DELETE FROM MEMBER WHERE TEL = '011'

SELECT * FROM MEMBER WHERE ID = '200' AND TEL = '011'

SELECT * FROM MEMBER WHERE ID = '200' OR TEL = '011'

SELECT * FROM MEMBER ORDER BY ID 

CREATE TABLE PRODUCT (
	ID VARCHAR2(200),
	NAME VARCHAR2(200),
	CONTENT VARCHAR2(200),
	PRICE VARCHAR2(200),
	COMPANY VARCHAR2(200),
	IMG VARCHAR2(200)
)

SELECT * FROM PRODUCT ORDER BY PRICE DESC -- 1번

SELECT NAME, CONTENT, PRICE FROM PRODUCT ORDER BY COMPANY ASC -- 2번

SELECT NAME, PRICE FROM PRODUCT WHERE ID = '100' --3번

SELECT NAME, COMPANY FROM PRODUCT WHERE PRICE = '5000' -- 4번

SELECT NAME, IMG FROM PRODUCT WHERE ID = '100' AND PRICE = '1000' -- 5번

SELECT COMPANY, NAME FROM PRODUCT WHERE COMPANY = 'c100' -- 6번

SELECT NAME, PRICE  FROM PRODUCT WHERE COMPANY = 'c100' -- 7번

UPDATE PRODUCT SET CONTENT = '품절' WHERE PRICE = '5000' -- 8번

UPDATE PRODUCT SET IMG = 'o.png', PRICE = '10000' WHERE ID = '100' OR ID = '102' -- 9번

UPDATE PRODUCT SET COMPANY = 'apple', NAME = 'appleshoes' WHERE ID = '101' -- 10번

DELETE FROM PRODUCT WHERE NAME = 'SHOES1' OR ID = '107' -- 11번

DELETE FROM PRODUCT WHERE COMPANY = 'c100' -- 12번

DELETE FROM PRODUCT -- 13번

DROP TABLE PRODUCT -- 14번
